// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package botcmds

import "reflect"

var Functions = map[string]reflect.Value{
	"Active": reflect.ValueOf(Active),
	"Cancel": reflect.ValueOf(Cancel),
	"Groups": reflect.ValueOf(Groups),
	"Lookout": reflect.ValueOf(Lookout),
}

